# Generated by Django 3.0.3 on 2020-06-09 18:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('complete', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2020, 6, 9, 18, 7, 28, 726236, tzinfo=utc))),
            ],
        ),
    ]
