# Generated by Django 3.0.3 on 2020-06-09 18:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 6, 9, 18, 8, 7, 397437, tzinfo=utc)),
        ),
    ]
