# Generated by Django 3.0.3 on 2020-06-09 19:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200609_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 6, 9, 19, 59, 56, 538680, tzinfo=utc)),
        ),
    ]
